### ISSUE TITLE
有体验版本吗

### ISSUE THREAD

**Issue by Qlijunjie** [anyRTC/anyRTC-WhiteBoard-Web#1]
有体验版本吗

**Comment by chudongvip** [comment]
可以试试新版本的 SDK 
快速开始：https://docs.anyrtc.io/cn/WhiteBoard/run/whiteboard_demo/run_demo_whiteboard_web
API: https://docs.anyrtc.io/cn/WhiteBoard/api-ref/whiteboard_web/overview
